### ISSUE TITLE
gitignored data directory and a download script?

### ISSUE THREAD

**Issue by mccalluc** [NCBI-Codeathons/automated-sc-RNA-seq-analysis-in-the-cloud#2]
@aopisco : Will we we working with the data at https://figshare.com/articles/Processed_files_to_use_with_scanpy_/8273102 ? Would a simple script that downloads the data to a local gitignored directory help us get started? Or is that premature?

Assign back to me to implement, if that's the right direction.

**Comment by aopisco** [comment]
no, with the data available from this bucket: https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis/

where do you think it's better to start? with h5ad files?

**Comment by mccalluc** [comment]
Not sure: I think I was imagining there being some small sample data that we'd download to get started with... but I don't think I know what the goal is. If it's something we'll work out on Wednesday, great, or if you know what the plan is, and you'd like to add it to the README, that works, too.

**Comment by mccalluc** [comment]
`data/` is in place. Closing.
